### ISSUE TITLE
DNS server change not working with nar_santricity_management role

### ISSUE THREAD

**Issue by mamoep** [netappeseries/santricity#14]
I have running eSeries nodes and wanted to change the DNS server addresses. It seems the management role ignores that the DNS server variables differ from the current configuration.

Collection version: 1.2.13

group_vars:
```
eseries_management_interfaces:
  dns_config_method: static
  dns_address: 4.4.4.4
  dns_address_backup: 8.8.8.8
```
