### ISSUE TITLE
Setting client certificates with the role nar_santricity_management fails with "template error"

### ISSUE THREAD

**Issue by mamoep** [netappeseries/santricity#5]
I tried to use the role nar_santricity_management to set the client certificates but it fails with "Template error while templating string: no test named 'in'. String".

**Playbook:**
```yaml
- hosts: eseries_nodes
  become: false
  gather_facts: false
  collections:
    - netapp_eseries.santricity
  vars:
    eseries_system_api_url: https://{{ inventory_hostname }}:8443/devmgr/v2
    eseries_system_username: "{{ username }}"
    eseries_system_password: "{{ password }}"
    eseries_validate_certs: false
    eseries_client_certificate_certificates:
      - /path/cert_intermediat.crt
      - /path/cert_root.crt
  tasks:
  - name: Set eSeries management parameters
    import_role:
      name: nar_santricity_management
```

**Error**
```
TASK [netapp_eseries.santricity.nar_santricity_management : Ensure client certificates are installed] *****************************************************************************
task path: /home/user/.ansible/collections/ansible_collections/netapp_eseries/santricity/roles/nar_santricity_management/tasks/security.yml:37
fatal: [host]: FAILED! => {
    "msg": "An unhandled exception occurred while templating '{%- set certs = [] -%}\n\n{#- Add common client certificates -#}\n{%- if eseries_client_certificate_common_certificates is defined -%}\n  {%- if eseries_client_certificate_common_certificates is string() -%}\n    {%- if certs.append(eseries_client_certificate_common_certificates) -%}{%- endif -%}\n  {%- elif eseries_client_certificate_common_certificates is iterable() -%}\n    {%- if certs.extend(eseries_client_certificate_common_certificates) -%}{%- endif -%}\n  {%- endif -%}\n{%- endif -%}\n\n{#- Add controller A client certificates -#}\n{%- if eseries_client_certificate_certificates is defined -%}\n  {%- if eseries_client_certificate_certificates is string() and eseries_client_certificate_certificates is not in certs -%}\n    {%- if certs.append(eseries_client_certificate_certificates) -%}{%- endif -%}\n  {%- elif eseries_client_certificate_certificates is iterable() -%}\n    {%- for client_cert in eseries_client_certificate_certificates if client_cert not in certs -%}\n      {%- if certs.append(client_cert) -%}{%- endif -%}\n    {%- endfor -%}\n  {%- endif -%}\n{%- endif -%}\n{{- certs -}}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: template error while templating string: no test named 'in'. String: {%- set certs = [] -%}\n\n{#- Add common client certificates -#}\n{%- if eseries_client_certificate_common_certificates is defined -%}\n  {%- if eseries_client_certificate_common_certificates is string() -%}\n    {%- if certs.append(eseries_client_certificate_common_certificates) -%}{%- endif -%}\n  {%- elif eseries_client_certificate_common_certificates is iterable() -%}\n    {%- if certs.extend(eseries_client_certificate_common_certificates) -%}{%- endif -%}\n  {%- endif -%}\n{%- endif -%}\n\n{#- Add controller A client certificates -#}\n{%- if eseries_client_certificate_certificates is defined -%}\n  {%- if eseries_client_certificate_certificates is string() and eseries_client_certificate_certificates is not in certs -%}\n    {%- if certs.append(eseries_client_certificate_certificates) -%}{%- endif -%}\n  {%- elif eseries_client_certificate_certificates is iterable() -%}\n    {%- for client_cert in eseries_client_certificate_certificates if client_cert not in certs -%}\n      {%- if certs.append(client_cert) -%}{%- endif -%}\n    {%- endfor -%}\n  {%- endif -%}\n{%- endif -%}\n{{- certs -}}"
}
```

**Ansible-Version**
RHEL 7 in use
```
$ ansible --version
ansible 2.9.17
  config file = /ansible/private/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug 13 2020, 02:51:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```
